### ISSUE TITLE
Different behavior with command based tester

### ISSUE THREAD

**Issue by pderouen** [Origen-SDK/origen_jtag#16]
https://github.com/Origen-SDK/origen_jtag/blob/904dd21a07e09fade7eb0e78a869fec693532d3a/lib/origen_jtag/driver.rb#L483

If the tester responds to <code>write_ir</code> the ir value is updated regardless of the previous value shifted to the ir. Otherwise, the ir value is shifted only if it's not the same as the previous value shifted (for force is set). I'm working on an internal command based plugin (that responds to write_ir) and stumbled across this behavior. It prevents the resultant output from working correctly. Back to back dr writes are expected during a sequence in the pattern.

Do we intentionally have the code setup this way? Is the intention to have the command based tester decide what to do? I can't think of why it might be different. If this behavior isn't intentional, I'd like to wrap the command based tester behavior in the comparison as well.

**Comment by ginty** [comment]
I don't think the intention was really to skip that redundancy checking.
I think it has been written more from the viewpoint of "if this tester handless write IR then just completely defer to that", and so it branches out at the earliest opportunity.
However, I think it is reasonable for the JTAG driver to track the IR state instead of the tester and it is an oversight that it doesn't.
So I agree with the change you want to make here and I doubt there will be any ill effects from implementing it.
